######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 21:17:33 2015
######################################################################

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += quit.cpp
