######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 21:29:21 2015
######################################################################

TEMPLATE = app
TARGET = gotocelldialog
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
