######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 21:21:38 2015
######################################################################

TEMPLATE = app
TARGET = FindDialog
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
