######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 21:15:44 2015
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += hello.cpp
