######################################################################
# Automatically generated by qmake (3.0) Mon Aug 24 13:47:06 2015
######################################################################

TEMPLATE = app
TARGET = gtcd
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += gtcd.h
SOURCES += gtcd.cpp main.cpp
