######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 21:16:34 2015
######################################################################

TEMPLATE = app
TARGET = age
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += age.cpp
