######################################################################
# Automatically generated by qmake (3.0) Sat Sep 5 16:02:06 2015
######################################################################

TEMPLATE = app
TARGET = MailHandling
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -Wpedantic

# Input
HEADERS += folder.h message.h
SOURCES += folder.cpp main.cpp message.cpp
