######################################################################
# Automatically generated by qmake (3.0) Mon Aug 24 16:48:14 2015
######################################################################

TEMPLATE = app
TARGET = sort
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += sortdialog.h ui_sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
