######################################################################
# Automatically generated by qmake (3.0) Thu Sep 3 14:10:40 2015
######################################################################

TEMPLATE = app
TARGET = BatteryWatcher
INCLUDEPATH += .

QT += widgets

QMAKE_CXXFLAGS = -std=c++11 -Wall -Wextra -Wpedantic

# Input
SOURCES += BatteryWatcher.cpp
